var customerData = 
[
{ 
    tableTitle: "UNIVERSAL TESTING  MACHINES 100T/ 60T / 40T CAPACITY.",
    tableHeader: ["Sl.","Company  Name  &  Address","Capacity"],
    tableData: [
                ["01.","ANKIT METAL &   POWER   WORKS, Kolkata","100 T"],
                ["02.","AMBE   STELLS  (P)  LTD.   Nepal.","100T(E)"],
                ["03.","BASHUNDHARA  STEELS LTD, Dacca","100 T"],
                ["04.","B.D. CASTINGS.,  Howrah  **","100T(E)"],
                ["05.","BRAHM  (ALLOYS)  PVT .  LTD  (Durgapur)","100T"],
                ["06.","BDG  METAL  &  POWER  LIMITED. ( BANKURA )","100T(E)"],
                ["07.","CALCUTTA  SPRINGS  LTD.  Hooghly **","100T"],
                ["08.","DRUK  IRON  &  STEEL,  Bhutan **","100T(E)"],
                ["09.","FABULOUS COMMERCIAL (P) LTD. Siliguri","100T"],
                ["10.","KOHINOOR  STEEL (P)  LTD,  ( Jhar)","100T(E)"],
                ["11.","KALINGA  METALLICS  & POWER PVT. LTD.  Orissa.","100T(E)"],
                ["12.","LAXMI   STEELS. ( Nepal )","100T(E)"],
                ["13.","PURULIA  METAL  CASTING (P)  LTD.  Purulia.","100T"],
                ["14.","R.S. ISPAT   PVT.  LTD.,  Dankuni **","100T"],
                ["15","RASHMI  METALIKS  LTD, Kharagpur.","100T (E)"],
                ["16.","SHRI   BADRINARAIN   ALLOYS.  LTD., Calcutta **","100T (E)"],
                ["17.","SHYAM   STEELS   LTD., Durgapur ** ","100T"],
                ["18","SHYAM   STEELS   LTD., Durgapur**","100T"],
                ["19.","SHYAM  STEELS   LTD, Durgapur**","200(E)"],
                ["20.","SHIVA   RE  ROLLERS  (P)  LTD,  Orissa.","100 T"],
                ["21.","SHRI  RAMRUPAI   BALAJI  STEEL. Durgapur**","100T"],
                ["22.","SCAN   STEELS   LTD , Orrisa.","100T"],
                ["23.","SHYAM  METALICS AND  ENERGY  LIMITED. (Orissa)","100T(E)"],
                ["24.","SRMB  SRIJAN  LTD , Durgapur**","100T"],
                ["25.","SHIVA  RE–ROLLERS  PVT. LTD, Rourkela","100T"],
                ["26.","SHREE GOPAL CONCRETE  PVT . LTD. Burdwan.","100 E"],
                ["27.","JAI   BALAJI. Durgapur","    100T"],
                ["28.","JAGADAMBA  INDUSTRIES.Durgapur.","100T"],
                ["28.","TOFFAN  STEELS  INDUSTRIES PVT. LTD. Murshidabad","100T(E)"],
                ["29.","VIKASH  METALS  &  POWER  LTD.","100 T"],
                ["30.","MAITHAN  STEEL  POWER  LTD, (Asansol)","100 T"],
                ["31.","MODERN  INDIA STEEL  ROLLING  MILLS  PVT. LTD","100T(E)"],
                ["32.","N N ISPAT PVT. LTD. Burdwan.","100T "],
                ["33.","RAIC INTEGRATED SPONGE AND POWER PVT. LTD.","100 MPC"],
                ["34.","BYRNIHAT  ISPAT   LTD,  Meghalaya","     60T"],
                ["35.","COSMOS  ISPAT  PVT . LTD.   ( Raipur )","60T"],
                ["36.","DURGAPUR  STEELS  LTD., Durgapur","60 T"],
                ["37.","DRUK  IRON  &  STEEL,  Bhutan **","60 T"],
                ["38.","GRIHASHAKTI  STEEL (P) LTD, (Guw)","60 T"],
                ["39.","GIRIRAJ   ISPAT  PVT.  LTD,  Howrah","60 T"],
                ["40.","HAMA IRON & STEEL IND. (P) LTD., Nepal","60T"],
                ["41.","MANGAL  CHAND  ROLLING  MILL, Asansol","60 T"],
                ["42.","MICKY  METALS  LTD ,   Suri, ","60 T"],
                ["43.","PAWAN   CASTING  PVT.  LTD, (MEGH)","60 T"],
                ["44.","PRAKASH  STEEL  PRDUCTS  PVT. LTD.","60 T"],
                ["45.","RATAN  REROLLERS, Calcutta ","60 T"],
                ["46.","RATUSARIA   STEELS, Raipur, ","60 T"],
                ["47.","RADHE   STRIPS,  Raipur","60 T"],
                ["48.","SHYAM   STEELS   LTD., Durgapur  **","60 T(E)"],
                ["49.","SHYAM   STEELS   LTD., Howrah**","60T"],
                ["50.","SHYAM   STEELS   LTD., Howrah**","60T"],
                ["51.","SHRIRAM   STEELS, Giridih","60 T"],
                ["52.","SHREE GANESH  ROLLING  MILLS  (P)  LTD, Orissa","60 T"],
                ["53.","SHRI  RAMRUPAI  BALAJI  STEEL. Durgapur**","60 T"],
                ["54.","SACHIN   ISPAT  PVT  LTD.  ","60 T"],
                ["55.","SHREE  AMBIKA  MATALLIKS. Howrah.","60 T"],
                ["56.","JAI   BALAJI. Durgapur","60T"],
                ["57.","NISSAN  FERRO – CAST  LIMITED, (Hooghly)","60 T"],
                ["58.","OM  STEEL. Howrah.","60 T"],
                ["59.","AMBICA   ROLLING   MILLS,   Rourkela","40 T"],
                ["60.","ALLIEDINDIA  IRON  &  STEELS (P) LTD, Giridih","40 T"],
                ["61.","B.D. CASTINGS.,  Howrah. **","40 T"],
                ["62.","BABA   ISPAT  (P)  LTD,  Ranigung","40 T"],
                ["63.","BEEKAY  BROTHERS,  Kolkata","40 T"],
                ["64.","BENGAL  HAMMER  LTD., Howrah","40 T"],
                ["65.","BHAWANI  METALS  PVT. LTD.,  Deoghar","40 T"],
                ["66.","BAJRANGBALI  RE – ROLLERS. PVT. LTD., (Rourkela)","40T"],
                ["67.","GANESH   ROLLING   MILLS , Rourkela.","40 T"],
                ["68.","I.C. ISPAT (PVT.) LTD., Siliguri**","40 T"],
                ["69.","MILLENIUM   METALLOYS   PVT.  LTD., Dibrugarh","40 T"],
                ["70.","PANKAJ    STEELS   (JHARKHAND)","40 T"],
                ["71.","R.S. ISPAT   PVT.  LTD.,  Dankuni **","40 T"],
                ["72.","SHRI   BADRINARAIN   ALLOYS.  LTD., Calcutta **","40 T"],
                ["73.","SIKKIM   ISPAT, Sikkim","40 T"],
                ["74.","SUPER  SMELTERS  LTD., Durgapur","40 T"],
                ["75.","SHREEJI  ISPAT  PVT. LTD., Bhubaneswar ","40 T"],
                ["76.","SHYAM   STEELS   LTD,  Kolkata **","40 T "],
                ["77.","SHREE  GOPAL  HI -TECH,  Durgapur**","40 T"],
                ["78.","SREE  RAM  RE ROLLERS  PVT . LTD, Rourkela","40 T"],
                ["79.","SALASAR   STEELS , Giridih.","40 T"],
                ["80.","SHREE  MAHALAXMI  VINIMAY  LTD., Kolkata","40 T"],
                ["81.","SRMB SRIJAN  LTD,  Kolkata**","40T"],
                ["82.","SRMB SRIJAN  LTD,  Siliguri**","40 T"],
                ["83.","SRMB  SRIJAN  LTD, Ernakulam**","40 T"],
                ["84.","SRMB  SRIJAN  LTD, Jamshedpur**","40 T"],
                ["85.","SRMB  SRIJAN  LTD, Baharampur**","40 T"],
                ["86.","SRMB  SRIJAN  LTD,  Balugaht**","40 T"],
                ["87.","SRMB  SRIJAN  LTD,  Michel  Nagar **","40 T"],
                ["88.","SRMB  SRIJAN  LTD,  Jaipur **","40 T"],
                ["89.","SRMB  SRIJAN  LTD, Kerala **","40 T"],
                ["90.","SRMB  SRIJAN  LTD, Raigunj **","40 T"],
                ["91.","SRMB  SRJAN  LTD,  Malda ** ","40 T"],
                ["92.","SRMB  SRJAN  LTD,  Tipura ** ","40 T"],
                ["93.","SRMB  SRJAN  LTD,  Karnataka ** ","40 T"],
                ["94.","SRMB  SRJAN  LTD,  Karnataka ** ","40 T"],
                ["95.","SARDA  REROLLERS  MILLS, Rourkela","40 T"],
                ["96.","JUHI  INDUSTRIES  (P)  LTD. Jamshedpur","40 T"],
                ["97.","TIJIYA   STEELS PVT. LTD., Kolkata ","40 T"],
                ["98.","VINITA   PROJECTS  (P)  LIMITED, Howrah","40 T"],
                ["99.","MAGNUM  HI – TECH  METAL. Howrah.","40T"],
                ["100.","NORTH EAST  ROLLING  MILL (P) LTD, (Assam).","40 T"],
                ["101.","YESH  ALLOY. Ranchi.","40 T"]
            ]
},

{
    tableTitle: "SERVO   UNIVERSAL  TESTING  MACHINES, SERVO TENSILE TESTING MACHINES   &  COMPUTERISED    BRINEL  HARDNESS  TESTER",
    tableHeader: ["Sl.","Company  Name  &  Address","Capacity"],
    tableData: [ 
        ["1","SHREE  AMBIKA   METALS.   (Howrah)","60T  / 3000 kgf"],
        ["2","TECHMA   ENGG. ENTERPRISE. ( Domjur  Howrah )","60T   / 3000 kgf"],
        ["3","GANAPATI   INDUSTRIAL   CORPORATION.  (Raipur)","3000 kgf"],
        ["4","JEKAY   INTRNL .  TRACK   (P)   LTD.   (Raipur)","60T"],
        ["5","SHREE   LAXMI   IRON  &  STEEL.  (Howrah)","60T  / 3000 kgf"],
        ["6","BHASKAR   INDUSTRIAL   DEVELOPMENT. (KHARDA)","60T  / 3000 kgf"],
        ["7","SURYA   ALLOYS  PVT  LTD.  (Durgapur)","60T  / 3000 kgf"],
        ["8","CALCUTTA  SPRING  PVT  LTD. ( Howrah )","20T  / 3000 kgf"],
        ["9","SURYA   ALLOYS  INDUSTRIAL  LTD.  (MEGHALAYA)","20T  / 3000 kgf"],
        ["10","BHASKAR  SHRACHI  ALLOYS   LTD.  ((KHARDA)","20T"]

    ]   
},

{
    tableTitle: "DYNAMIC BALANCING MACHINE",
    tableHeader: ["Sl.","Company  Name  &  Address","Capacity"],
    tableData: [ 
        ["1","AIR TECHNIKO INDUSTRIES, Kolkata","3000"],
        ["2","METAL & MINIRALS TESTING LAB, Howrah","10000"],
        ["3","CALCUTTA PUMPS & INDUSTRIES, Kolkata","50"],
        ["4","TAGO ENGINEERING CO, Howrah","10000"],
        ["5","DAS ENGINEERING WORKS, Kolkata","3000"],
        ["6","WESMAN ENGINEERING CO, Howrah","1000"],
        ["7","MAITRYANI ELECTRICALS, Kolkata","30"],
        ["8","KHANDALWAL INDUSTRIES, Dhanbad","1000"],
        ["9","SUGAN ENGINEERING (PVT) LTD, Howrah","10"],
        ["10","INSPECTION INDIA, Calcutta","300"],
        ["11","METAL & MINIRALS TESTING LAB, Howrah","300"],
        ["12","JADAVPUR UNIVERSITY, Calcutta","300"],
        ["13","CONTINENTAL PROFILES, Durgapur","1000"],
        ["14","IND. RESEARCH & CONSULTANCY, Howrah","300"],
        ["15","HI-TECH BALANCERS & ENGINEERS, Howrah","30"],
        ["16","HI-TECH BALANCERS & ENGINEERS, Howrah","300"],
        ["17","HI-TECH BALANCERS & ENGINEERS, Howrah","3000"],
        ["18","IND.DEV & TESTING LAB, Howrah","1000"],
        ["19","POWER & MACHINERY CONST. CO. Calcutta","300"],
        ["20","UNIVERSAL ENGINEERING CO, Kolkata","50"],
        ["21","G B M AGENCY, Kolkata","1000"],
        ["22","PRIME MOVER INDIA, Kolkata","300"],
        ["23","SUGAN MACHINES & EQUIPMENTS, Kolkata","10"],
        ["24","AIR TECHNIKO (INDIA)  PVT LTD, Kolkata","300"],
        ["25","SANDIP INDUSTRIES, Kolkata","10"],
        ["26","MISHRA & BROTHERS, Singroli","650"],
        ["27","GENMOT (INDIA) PVT LTD, Kolkata","300"],
        ["28","DAMANI ENGINEERING CO, Howrah","1000"],
        ["28","PRODYOT ENGINEERING WORKS, Howrah","300"],
        ["29","RELIANCE ENGINEERING CONCERN, Howrah","50"],
        ["30","IRC PROJECT SERVICES, Howrah","10000"],
        ["31","M P ENGINEERING WORKS, Orissa","300"],
        ["32","INDUSTRIAL DEVELOPMENT TEST LAB, Howrah","30"],
        ["33","AIR TECHNIKO INDUSTRIES, Kolkata","300"],
        ["34","BENGAL TOOLS, Kolkata","7000"],
        ["35","CALCUTTA ENGINEERING","300"],
        ["36","ENVIROTREAT PVT LTD","3000"],
        ["37","INDUSTRIAL DEVELOPMENT TEST LAB, Howrah","1000"],
        ["38","IRC PROJECT SERVICE, Howrah","100"],
        ["39","IRC PROJECT SERVICE, Howrah","3000"],
        ["40","MACOLYTE POLYMERS","10"],
        ["41","MA MANASA","300"],
        ["42","MECEN ENGINEERS","300"],
        ["43","MARCO BLOWERS","300"],
        ["44","MAXFLOW FANS","300"],
        ["45","PASKO","50"],
        ["46","WELLTECH, Howrah","1000"],
        ["47","DAS PROCESSING ","3000"],
        ["48","DYNAMIC INDIAN","1000"],
        ["49","KGB","1000"],
        ["50","NATIONAL STORES","100"],
        ["51","GENMOT INDIA PVT LTD","250"],
        ["52","MICRO ENGINEERING","300"]        
    ] 
}


]